name: Docker Image CI

on:
  push:
    branches:
      - '**'

env:
  TEST_TAG: ${{ secrets.DOCKERHUB_USERNAME }}/docker-devops-tools:test
  DOCKERHUB_LATEST_TAG: ${{ secrets.DOCKERHUB_USERNAME }}/docker-devops-tools:latest

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and export to Docker
        uses: docker/build-push-action@v3
        with:
          context: .
          load: true
          tags: ${{ env.TEST_TAG }}
      -
        name: Test
        run: |
          docker run --rm ${{ env.TEST_TAG }} terraform --version
          docker run --rm ${{ env.TEST_TAG }} ansible --version
          docker run --rm ${{ env.TEST_TAG }} terragrunt --version
          docker run --rm ${{ env.TEST_TAG }} aws --version
          docker run --rm ${{ env.TEST_TAG }} packer --version

      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            ${{ env.DOCKERHUB_LATEST_TAG}}
